/**
 * Markdown Template — Default output format
 *
 * Produces identical output to MarkdownGenerator.generateFromPostProcess().
 * This is the reference template that all others derive context from.
 */

import type { OutputTemplate, TemplateContext, TemplateOutput } from './types';
import {
  formatTimestamp,
  formatDate,
  computeSessionDuration,
  wrapTranscription,
  generateSegmentTitle,
  computeRelativeFramePath,
  mapFramesToSegments,
} from './helpers';

const REPORT_SUPPORT_LINE = '*If this report saved you time, support development: [Ko-fi](https://ko-fi.com/eddiesanjuan)*';

export const markdownTemplate: OutputTemplate = {
  name: 'markdown',
  description: 'Default Markdown format — AI-ready, llms.txt-inspired structured document',
  fileExtension: '.md',

  render(context: TemplateContext): TemplateOutput {
    const { result, sessionDir, timestamp } = context;
    const { transcriptSegments, extractedFrames } = result;
    const sessionTimestamp = formatDate(new Date(timestamp ?? Date.now()));

    const sessionDuration = computeSessionDuration(transcriptSegments);

    let md = `# markupR Session — ${sessionTimestamp}\n`;
    md += `> Segments: ${transcriptSegments.length} | Frames: ${extractedFrames.length} | Duration: ${sessionDuration}\n\n`;

    if (transcriptSegments.length === 0) {
      md += `_No speech was detected during this recording._\n`;
      return { content: md, fileExtension: '.md' };
    }

    md += `## Transcript\n\n`;

    const segmentFrameMap = mapFramesToSegments(transcriptSegments, extractedFrames);

    for (let i = 0; i < transcriptSegments.length; i++) {
      const segment = transcriptSegments[i];
      const formattedTime = formatTimestamp(segment.startTime);
      const title = generateSegmentTitle(segment.text);

      md += `### [${formattedTime}] ${title}\n`;
      md += `> ${wrapTranscription(segment.text)}\n\n`;

      const frames = segmentFrameMap.get(i);
      if (frames && frames.length > 0) {
        for (const frame of frames) {
          const frameTimestamp = formatTimestamp(frame.timestamp);
          const relativePath = computeRelativeFramePath(frame.path, sessionDir);
          md += `![Frame at ${frameTimestamp}](${relativePath})\n\n`;
        }
      }
    }

    md += `---\n*Generated by [markupR](https://markupr.com)*\n${REPORT_SUPPORT_LINE}\n`;

    return { content: md, fileExtension: '.md' };
  },
};
