name: 'markupr Analyze'
description: 'Analyze screen recordings and post structured visual feedback reports on PRs'
author: 'Eddie San Juan'

branding:
  icon: 'camera'
  color: 'orange'

inputs:
  video-path:
    description: 'Path to video file or directory of recordings'
    required: true
  github-token:
    description: 'GitHub token for PR comments and issue creation'
    required: true
    default: ${{ github.token }}
  template:
    description: 'Output template (markdown, json, github-issue, linear, jira)'
    required: false
    default: 'markdown'
  create-issues:
    description: 'Create GitHub Issues from each feedback item'
    required: false
    default: 'false'
  comment-on-pr:
    description: 'Post the report as a PR comment'
    required: false
    default: 'true'
  repo:
    description: 'Target repo for issues (owner/repo format). Defaults to current repo.'
    required: false
    default: ''

outputs:
  report-path:
    description: 'Path to the generated markdown report'
    value: ${{ steps.analyze.outputs.report-path }}
  issues-created:
    description: 'Number of GitHub issues created (0 if create-issues is false)'
    value: ${{ steps.push.outputs.issues-created }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ ! -e "${{ inputs.video-path }}" ]; then
          echo "::error::Video path not found: ${{ inputs.video-path }}"
          exit 1
        fi

    - name: Ensure ffmpeg is available
      shell: bash
      run: |
        if ! command -v ffmpeg &> /dev/null; then
          echo "Installing ffmpeg..."
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update -qq && sudo apt-get install -y -qq ffmpeg
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install ffmpeg
          else
            echo "::error::ffmpeg not found. Please install ffmpeg on this runner."
            exit 1
          fi
        fi
        echo "ffmpeg version: $(ffmpeg -version | head -1)"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Analyze recordings
      id: analyze
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        VIDEO_PATH="${{ inputs.video-path }}"
        TEMPLATE="${{ inputs.template }}"
        OUTPUT_DIR="${{ runner.temp }}/markupr-output"

        mkdir -p "$OUTPUT_DIR"

        # Process a single file or all videos in a directory
        process_video() {
          local video="$1"
          local out_dir="$2"
          echo "::group::Analyzing $(basename "$video")"
          npx --yes markupr@latest analyze "$video" --output "$out_dir" --verbose 2>&1 || true
          echo "::endgroup::"
        }

        if [ -d "$VIDEO_PATH" ]; then
          echo "Processing directory: $VIDEO_PATH"
          found=0
          for video in "$VIDEO_PATH"/*.{mp4,mov,webm,mkv,avi}; do
            [ -f "$video" ] || continue
            found=1
            basename=$(basename "$video" | sed 's/\.[^.]*$//')
            process_video "$video" "$OUTPUT_DIR/$basename"
          done
          if [ "$found" -eq 0 ]; then
            echo "::warning::No video files found in $VIDEO_PATH"
          fi
        else
          process_video "$VIDEO_PATH" "$OUTPUT_DIR"
        fi

        # Find the generated report(s)
        REPORT=$(find "$OUTPUT_DIR" -name "*.md" -type f | head -1)
        if [ -z "$REPORT" ]; then
          echo "::warning::No report generated. The recording may have no audio or the pipeline encountered an error."
          echo "report-path=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "report-path=$REPORT" >> "$GITHUB_OUTPUT"
        echo "output-dir=$OUTPUT_DIR" >> "$GITHUB_OUTPUT"
        echo "Report generated: $REPORT"

    - name: Post PR comment
      if: inputs.comment-on-pr == 'true' && steps.analyze.outputs.report-path != '' && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        REPORT="${{ steps.analyze.outputs.report-path }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO="${{ github.repository }}"

        # Build the comment body
        COMMENT_BODY="## markupr Visual Feedback Report

        $(cat "$REPORT")

        ---
        *Generated by [markupr](https://github.com/eddiesanjuan/markupr) in CI*"

        # Truncate if too long for GitHub comment (max ~65536 chars)
        MAX_LEN=60000
        if [ ${#COMMENT_BODY} -gt $MAX_LEN ]; then
          COMMENT_BODY="${COMMENT_BODY:0:$MAX_LEN}

        ...

        > Report truncated. See the full report in the uploaded artifact."
        fi

        # Check for existing markupr comment to update instead of creating duplicates
        EXISTING_COMMENT_ID=$(gh api \
          "repos/$REPO/issues/$PR_NUMBER/comments" \
          --jq '.[] | select(.body | startswith("## markupr Visual Feedback Report")) | .id' \
          2>/dev/null | head -1)

        if [ -n "$EXISTING_COMMENT_ID" ]; then
          echo "Updating existing comment $EXISTING_COMMENT_ID"
          gh api \
            --method PATCH \
            "repos/$REPO/issues/comments/$EXISTING_COMMENT_ID" \
            -f body="$COMMENT_BODY"
        else
          echo "Creating new PR comment"
          gh api \
            --method POST \
            "repos/$REPO/issues/$PR_NUMBER/comments" \
            -f body="$COMMENT_BODY"
        fi

        echo "Posted report to PR #$PR_NUMBER"

    - name: Create GitHub Issues
      id: push
      if: inputs.create-issues == 'true' && steps.analyze.outputs.report-path != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        REPORT="${{ steps.analyze.outputs.report-path }}"
        TARGET_REPO="${{ inputs.repo }}"

        if [ -z "$TARGET_REPO" ]; then
          TARGET_REPO="${{ github.repository }}"
        fi

        # Parse owner/repo
        OWNER=$(echo "$TARGET_REPO" | cut -d'/' -f1)
        REPO_NAME=$(echo "$TARGET_REPO" | cut -d'/' -f2)

        echo "Creating issues in $TARGET_REPO from $REPORT"
        OUTPUT=$(npx --yes markupr@latest push github "$REPORT" \
          --repo "$TARGET_REPO" 2>&1) || true

        echo "$OUTPUT"

        # Count created issues from output
        CREATED=$(echo "$OUTPUT" | grep -c "Created issue" || echo "0")
        echo "issues-created=$CREATED" >> "$GITHUB_OUTPUT"
        echo "Created $CREATED issue(s)"

    - name: Set default issues-created output
      if: inputs.create-issues != 'true' || steps.analyze.outputs.report-path == ''
      id: push-default
      shell: bash
      run: echo "issues-created=0" >> "$GITHUB_OUTPUT"

    - name: Upload report artifact
      if: steps.analyze.outputs.report-path != ''
      uses: actions/upload-artifact@v4
      with:
        name: markupr-report
        path: ${{ steps.analyze.outputs.output-dir }}
        retention-days: 30
