import { describe, expect, it } from 'vitest';
import { AUDIO_IPC_CHANNELS } from '../../src/main/audio/AudioCapture';
import { IPC_CHANNELS } from '../../src/shared/types';

describe('Audio IPC Channel Mapping', () => {
  it('uses the shared IPC channel names expected by preload', () => {
    expect(AUDIO_IPC_CHANNELS.REQUEST_DEVICES).toBe(IPC_CHANNELS.AUDIO_REQUEST_DEVICES);
    expect(AUDIO_IPC_CHANNELS.START_CAPTURE).toBe(IPC_CHANNELS.AUDIO_START_CAPTURE);
    expect(AUDIO_IPC_CHANNELS.STOP_CAPTURE).toBe(IPC_CHANNELS.AUDIO_STOP_CAPTURE);
    expect(AUDIO_IPC_CHANNELS.SET_DEVICE).toBe(IPC_CHANNELS.AUDIO_SET_DEVICE);
    expect(AUDIO_IPC_CHANNELS.AUDIO_CHUNK).toBe(IPC_CHANNELS.AUDIO_CHUNK);
    expect(AUDIO_IPC_CHANNELS.DEVICES_RESPONSE).toBe(IPC_CHANNELS.AUDIO_DEVICES_RESPONSE);
    expect(AUDIO_IPC_CHANNELS.CAPTURE_ERROR).toBe(IPC_CHANNELS.AUDIO_CAPTURE_ERROR);
    expect(AUDIO_IPC_CHANNELS.CAPTURE_STARTED).toBe(IPC_CHANNELS.AUDIO_CAPTURE_STARTED);
    expect(AUDIO_IPC_CHANNELS.CAPTURE_STOPPED).toBe(IPC_CHANNELS.AUDIO_CAPTURE_STOPPED);
  });
});
